# Generated by Django 4.1.3 on 2022-12-05 06:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_letter_emotion_letter_travel_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='openAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 15, 0, 0, 198148, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sendAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 6, 0, 43, 198148, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='LetterDelievery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='letter.letter')),
            ],
        ),
    ]
