# Generated by Django 4.1.3 on 2022-12-08 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0005_alter_letter_openat_alter_letter_sendat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='dday',
            field=models.PositiveSmallIntegerField(default=365),
        ),
        migrations.AlterField(
            model_name='letter',
            name='openAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 15, 0, 0, 326161, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sendAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 12, 39, 23, 326161, tzinfo=datetime.timezone.utc)),
        ),
    ]
