# Generated by Django 4.1.3 on 2022-12-08 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0006_letter_dday_alter_letter_openat_alter_letter_sendat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='dday',
        ),
        migrations.AlterField(
            model_name='letter',
            name='openAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 15, 0, 0, 1591, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sendAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 12, 49, 46, 1591, tzinfo=datetime.timezone.utc)),
        ),
    ]
